<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260608144952 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE booking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, begin_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, title VARCHAR(255) NOT NULL, duration_in_minutes INT DEFAULT NULL, ical_event JSONB NOT NULL, feed_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E00CEDDE51A5BC03 ON booking (feed_id)');
        $this->addSql('CREATE TABLE calendar (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, event_count INT NOT NULL, org_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6EA9A146F4837C1B ON calendar (org_id)');
        $this->addSql('CREATE TABLE contest (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, start_date DATE NOT NULL, duration INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE contest_photo (contest_id INT NOT NULL, photo_id INT NOT NULL, PRIMARY KEY (contest_id, photo_id))');
        $this->addSql('CREATE INDEX IDX_18CAF4301CD0F0DE ON contest_photo (contest_id)');
        $this->addSql('CREATE INDEX IDX_18CAF4307E9E4C8C ON contest_photo (photo_id)');
        $this->addSql('CREATE TABLE event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ical_event JSON DEFAULT NULL, start_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, title VARCHAR(255) NOT NULL, cal_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3BAE0AA77300D633 ON event (cal_id)');
        $this->addSql('CREATE TABLE feed (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url VARCHAR(255) NOT NULL, event_count INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, color VARCHAR(7) DEFAULT NULL, slug VARCHAR(255) NOT NULL, content TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_234044AB989D9B62 ON feed (slug)');
        $this->addSql('CREATE TABLE org (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, cal_count INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE photo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) DEFAULT NULL, camera_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, photographer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_14B7841853EC1A21 ON photo (photographer_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, birthdate DATE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE51A5BC03 FOREIGN KEY (feed_id) REFERENCES feed (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendar ADD CONSTRAINT FK_6EA9A146F4837C1B FOREIGN KEY (org_id) REFERENCES org (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contest_photo ADD CONSTRAINT FK_18CAF4301CD0F0DE FOREIGN KEY (contest_id) REFERENCES contest (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contest_photo ADD CONSTRAINT FK_18CAF4307E9E4C8C FOREIGN KEY (photo_id) REFERENCES photo (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA77300D633 FOREIGN KEY (cal_id) REFERENCES calendar (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE photo ADD CONSTRAINT FK_14B7841853EC1A21 FOREIGN KEY (photographer_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA toolkit_experimental');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDE51A5BC03');
        $this->addSql('ALTER TABLE calendar DROP CONSTRAINT FK_6EA9A146F4837C1B');
        $this->addSql('ALTER TABLE contest_photo DROP CONSTRAINT FK_18CAF4301CD0F0DE');
        $this->addSql('ALTER TABLE contest_photo DROP CONSTRAINT FK_18CAF4307E9E4C8C');
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA77300D633');
        $this->addSql('ALTER TABLE photo DROP CONSTRAINT FK_14B7841853EC1A21');
        $this->addSql('DROP TABLE booking');
        $this->addSql('DROP TABLE calendar');
        $this->addSql('DROP TABLE contest');
        $this->addSql('DROP TABLE contest_photo');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE feed');
        $this->addSql('DROP TABLE org');
        $this->addSql('DROP TABLE photo');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
